### ISSUE TITLE
Setup percussion midi note defaults

### ISSUE THREAD

**Issue by Alex-L-Crane** [JoshuaBThompson/WristBand#11]
The following will ultimately be the default settings on the device:

Percussion midi notes should be sent on channel 10. 

Notes:
#35 (B0) Bass Drum 2
#36 (C1) Bass Drum 1
#38 (D1) Snare Drum
#42 (F1) Closed Hi Hats

**Comment by JoshuaBThompson** [comment]
Will work on this with iOs app development.

**Comment by JoshuaBThompson** [comment]
closing
