### ISSUE TITLE
Note change with rotation

### ISSUE THREAD

**Issue by Alex-L-Crane** [JoshuaBThompson/WristBand#14]
Make the note value change when egg is rotated. See drawing:

https://drive.google.com/file/d/0BwYGqGGFhTIdekVaLU1KcEpTekE/view?usp=sharing

**Comment by JoshuaBThompson** [comment]
1. To update rotation angle 1 note
-Open the 'LightBlue' application and click on JIDI 
-Click on the first row of the last table of data
-Enter '0A0041'  for note 65 since 41 in hex is 65 in decimal

for angle 2
Enter '0A0141'

**Comment by JoshuaBThompson** [comment]
rotation code completed and tested. Works, but needs a bit of optimization to reduce latency of rotation angle detection. Will make another issue for this when ready.
