### ISSUE TITLE
Consider adding midi program change message to toggle through instruments?

### ISSUE THREAD

**Issue by JoshuaBThompson** [JoshuaBThompson/WristBand#6]
According to the MIDI standard there is a program change message that allows you to tell the synthesizer / music software to change the instrument that is use to interpret the incoming midi note. 
Should we consider this? It might me useful to allow the user to use the egg device to toggle through instruments if needed. Just thinking!

Midi events table:
http://www.onicos.com/staff/iz/formats/midi-event.html

This website has a really good explanation of how to program in MIDI for different purposes:
http://www.cs.cmu.edu/~music/cmsip/readings/MIDI%20tutorial%20for%20programmers.html

**Comment by Alex-L-Crane** [comment]
Let's not worry about program change from the "egg" for now, although we should keep this in mind for future concepts. Let's use the following link as our online midi resource for now. I've been using it for a while and have found it to be useful:

http://computermusicresource.com/MIDI.resources.html

**Comment by JoshuaBThompson** [comment]
don't need
